strands-agents/tools

.gitignore
README.md
pyproject.toml
src/strands_tools/mem0_memory.py
tests/test_mem0.py

(Creating a new PR because of GitHub issue)
Adds support for `mem0_memory` tool to use memory with agents so that they can remember past states and personalize the experience of the users.
Yes, tested locally and added tests as well.

Add `mem0_memory` tool

---

.github/workflows/test-lint-pr.yml
pyproject.toml
src/strands_tools/mem0_memory.py
src/strands_tools/utils/user_input.py
tests/test_environment.py
tests/test_file_write.py
tests/test_python_repl.py
tests/test_shell.py

Per #17 - Windows compatibility is currently unknown and all changes are currently only tested on Linux.  For [parity with the SDK](https://github.com/strands-agents/sdk-python/blob/912e1104fd52e3da99767a644b90b22b7eb606de/.github/workflows/test-lint-pr.yml#L59), start running tests on MacOS & Windows.
On MacOS all tests were already passing.  On Windows I:
- added [`tzdata` as a dependency](https://pypi.org/project/tzdata/) to make the `current_time` work
- lazy loaded `session: PromptSession` in `get_user_input` to avoid import errors as part of the tests 
- updated [test_file_write.py](https://github.com/strands-agents/tools/compare/main...zastrowm:tools:windows_support#diff-a2998f18449d69766944a95d9058de448de22c38443a848876abaf22674df84a) to not use a permissions check, as the GitHub …

Add GitHub actions to run tests on Windows/MacOS & handle failures on Windows

---

pyproject.toml
src/strands_tools/load_tool.py
src/strands_tools/mem0_memory.py
src/strands_tools/slack.py
src/strands_tools/think.py
src/strands_tools/use_llm.py
tests/test_think.py
tests/test_use_llm.py

This PR enhances multiple tool components to better work together by improving interoperability and removing unnecessary dependencies.
- **think.py**: Now inherits parent agent's traces and tools to maintain context
- **load_tool.py**: Removed unnecessary `hot_reload_tools` dependency check
- **use_llm.py**: Now properly passes trace_attributes from parent agent
- **mem0_memory.py**: Code formatting and readability improvements
- **tests**: Updated to match new implementation patterns
```mermaid
flowchart TD
A[Parent Agent] -->|Create| B[think tool]
B -->|Call| C[use_llm]
C -->|Create new| D[Agent]
D -->|No access to parent tools| E[Limited functionality]
F[load_tool] -->|Check| G[hot_reload_tools flag]
G -->|Must be true| H[Load tool]
```
```mermaid
flowchart TD
A[Parent Agent] …
```

fix: improve tool interoperability and remove dependencies

---

pyproject.toml

Patch update to v0.1.2
N/A
N/A
Patch update to v0.1.2

Update version to v0.1.2

---

src/strands_tools/nova_reels.py
src/strands_tools/think.py
tests/test_think.py

Replace print() calls with console.print() in nova_reels and think tools
Currently these tools always print to stdout and don't respect the `STRANDS_TOOL_CONSOLE_MODE` environment variable.
* `hatch fmt`
* `hatch run test-lint`
* `hatch test`
- [-] I have added tests that prove my fix is effective or my feature works
- [-] I have updated the documentation accordingly
- [-] I have added an appropriate example to the documentation to outline the feature
- [-] Any dependent changes have been merged and published

fix: replace print() calls with console.print() in nova_reels and think tools

---

src/strands_tools/utils/user_input.py

To maintain parity with [agent builder](https://github.com/strands-agents/agent-builder/blob/7a54ef74c0ccc2472770e1c580952fdedaceb4df/src/strands_agents_builder/strands.py#L151), and fix the bug where the message "n" is sent as user input instead of moving onto the next line. 
https://github.com/strands-agents/tools/issues/38 

Remove default 'n' string from get_user_input methods

---

src/strands_tools/swarm.py
src/strands_tools/use_llm.py
tests/test_use_llm.py

Before, `use_llm` created an agent with the default `callback_handler`, which would make it print to stdout, even if the parent agent's `callback_handler` was changed from the default.
Now, `use_llm` checks for a `callback_handler` to use if passed, otherwise it tries to use the parent's `callback_handler`.  If that is missing, it falls back to using the previous default.
#54 
- I don't think this documentation update is necessary
- I have updated the doc string
- (I don't think this is necessary)
- By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

fix: Make use_llm respect callback_handler if passed, otherwise use parent agent's if available (#54)

---

src/strands_tools/mem0_memory.py

As the `allOf` was causing the issue in Mem0 Tool Spec so removing it.
[Link to related issues using #issue-number format]
* `hatch fmt --linter` - Yes
* `hatch fmt --formatter` - Yes
* `hatch test --all` - Yes

Remove allOf from Mem0 Tool Spec

---

tests/test_current_time.py

Current time tool test fails on Ubuntu Linux with TZ as US/Pacific. Details reported in bug #84
#84 
N/A
- [ x] Bug fix
Passed all the tests using hatch successfully

fix: Current time tool test fails on Ubuntu Linux with TZ as US/Pacific

---

pyproject.toml
src/strands_tools/mem0_memory.py
tests-integ/test_memory_tool.py

This RP is the entrypoint for our integration tests. This test creates real AWS resources (IAM Role, OpenSearch Collection, Bedrock KB) to validate the end-to-end functionality of the memory tool. 
Refactor is automated by hatch fmt.
[Link to related issues using #issue-number format]
- [ x] Other (please describe): test
- [ x] I have read the CONTRIBUTING document
- [ x] I have added tests that prove my fix is effective or my feature works
- [ x] I have updated the documentation accordingly
- [ x] I have added an appropriate example to the documentation to outline the feature
- [ x] My changes generate no new warnings
- [ x] Any …

test(memory): add an end-to-end integration test

---

src/strands_tools/generate_image.py
src/strands_tools/mem0_memory.py
tests/test_generate_image.py

The model currently used in generate_image tool has a hard-coded region for us-west-2. The model is no longer available in that region. The model is also being phased out of Amazon Bedrock. 
This PR will focus on the generate image tool to include the latest supported image generation models and their parameters. The fix has implemented support for all Stable Diffusion and Nova Canvas models. 
This will fix issue #75 
This will ensure that PR for multi modal examples is operating as expected- strands-agents/docs#93
1. Unit tests, formatter and linters has passed. 
2. Generated 4 invocation to models in scope - generating images using (Nova Canvas, SD Ultra, SD Core and SD 3.5).
- By submitting this pull request, I …

fix(generate_image): updating generate_image tool to support additional models in Amazon Bedrock

---

tests-integ/test_http_request.py
tests/test_mem0.py

[Provide a detailed description of the changes in this PR]
add serval tests for http_request tool.
[Link to related issues using #issue-number format]
- [ x] Other (please describe): Test
- [x ] I have read the CONTRIBUTING document
- [x ] I have added tests that prove my fix is effective or my feature works
- [x ] I have updated the documentation accordingly
- [x ] I have added an appropriate example to the documentation to outline the feature
- [x ] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published
- By submitting this pull request, I confirm that you can use, modify, copy, and …

test(http_request): add integration test for http_request tool

---

README.md
pyproject.toml

The dependencies for use_browser needed to be added to the `pyproject.toml` file a different way. 
Fix related to the following issue: https://github.com/strands-agents/tools/issues/116

fix: Fixing optional dependencies for use_browser tool

---

README.md
pyproject.toml

1. Aligned extra dependencies to match tool file name `a2a_client.py`
2. Update README 
n/a
n/a
- Cleanup/documentation

refactor(a2a): rename dependency target and update docs

---

tests/test_calculator.py

Update calculator tests to not use .invoke as 0.3.0 removed it
https://github.com/strands-agents/sdk-python/releases/tag/v0.3.0
- 

Update calculator tests to not use .invoke as 0.3.0 removed it

---

README.md
src/strands_tools/handoff_to_user.py
tests/test_handoff_to_user.py

This PR introduces a new handoff_to_user tool that enables agents to hand off control to users for human intervention in automated workflows. The tool provides two distinct modes of operation:
1. Interactive Mode (breakout_of_loop=False): Pauses execution to collect user input and continues with the response
2. Complete Handoff Mode (breakout_of_loop=True): Stops the event loop entirely and transfers control to the user
The tool follows the same architectural patterns as the existing stop tool, using ToolUse and ToolResult types with direct request_state access for event loop control. It provides a professional user interface with clear visual indicators and comprehensive error handling including graceful recovery from KeyboardInterrupt and other exceptions.
[No specific issues referenced …

feat: Add handoff to user tool

---

src/strands_tools/file_write.py

This PR improves terminal accessibility by changing the confirmation prompt text color in `file_write.py` from yellow to red. Yellow text is difficult to read in terminals with light themes (especially on macOS), as mentioned in [this blog post](https://jvns.ca/blog/2024/10/01/terminal-colours/). Red provides much better visibility on both light and dark backgrounds.
Updated line:
```python
get_user_input("<red><bold>Do you want to proceed with the file write?</bold> [y/*]</red>")
```
Closes #86
NA
Manually tested the file_write prompt with both light and dark terminal themes. Verified that the prompt displays correctly in red and functions as expected.
hatch fmt --linter ✅
hatch fmt --formatter ✅
hatch test --all ✅
- By submitting this pull request, I confirm that you can use, modify, …

fix: Change prompt color from yellow to red to improve readability

---

tests/test_python_repl.py

Fixed python_repl tests that were failing when the BYPASS_TOOL_CONSENT environment variable is set to true. The issue was caused by test isolation problems where environment variables were not properly mocked and REPL state was not cleared between tests.
N/A
N/A
Fixed the failing tests by:
- Adding proper environment variable mocking with `patch.dict("os.environ", {"BYPASS_TOOL_CONSENT": "false"}, clear=False)`
- Adding REPL state clearing with `python_repl.repl_state.clear_state()` before tests
- Ensuring test isolation for user rejection scenarios
Verified with:

test: fix python_repl tests failing with BYPASS_TOOL_CONSENT=true

---

README.md

Fixed missing code block formatting in the README.md file for the Code Interpreter section. Added proper markdown code blocks around the Python examples to improve readability and ensure proper syntax highlighting.
**Changes made:**
- Added opening ````python` code block marker
- Updated comment from "Create a session and execute code" to "Create a session" 
- Added "Execute Python code" comment for clarity
- Simplified the example code by removing pandas import
- Added closing ```` code block marker
N/A - Minor documentation formatting fix
N/A - This is the documentation fix itself
Verified that the markdown renders correctly with proper syntax highlighting:
* Manually reviewed the diff using `git diff`
* Confirmed that the code blocks now have proper markdown formatting
* No functional …

docs: fix code block formatting in README.md

---

src/strands_tools/swarm.py
tests/test_sleep.py
tests/test_swarm.py

Fixed a critical bug in the swarm tool where sub-agents were receiving tool names as strings instead of actual tool objects from the parent agent's registry. This caused sub-agents to treat tool names like "shell" and "editor" as file paths, attempting to load files like `./shell.py` and resulting in "Tool file not found" errors.
The fix modifies `_create_custom_agents()` to properly retrieve actual tool objects from `parent_agent.tool_registry.registry` instead of passing tool name strings, ensuring sub-agents receive functional tool instances.
Thanks for reporting: @westonbrown
Addresses bug reported by Aaron Brown regarding swarm sub-agents being unable to use tools due to incorrect tool object passing.
[Link to related associated PR in the agent-docs repo - if needed]
The change has …

fix(swarm): pass actual tool objects instead of tool name strings to sub-agents

---

src/strands_tools/file_read.py
tests/test_file_read.py

- Without this fix, if the contents of the file containing things like incomplete bracket pairs, then will we get an exception.
When working with some log files, I noticed `file_read` occasionally failed due to bracket characters in the logs. After tracing the code, I thought we should escape the strings before printing it out to the console which will do rendering according to markup in the strings.
* One test failed: `ERROR tests/test_a2a_client.py`. But this is obviously unrelated to my changes.

fix(file_read): escape strings before printing to console

---

README.md
pyproject.toml
src/strands_tools/diagram.py
tests/test_diagram.py

This PR introduces a diagram creation tool that supports multiple diagram types and output formats, making it easier for agents to generate visual representations of systems, architectures, and processes.
- This tool can be used to generate some basic diagrams:
- Cloud architecture diagrams (AWS services)
- Network diagrams
- Graph diagrams
- This tool can also be used to generate the 14 different UML (Unified Modeling Language) diagrams: 
- Structural
- Class
- Composite Structure
- Object
- Component
- Deployment
- Package
- Profile
- Behavioral
- State Machine
- Activity
- Use Case
- Sequence
- Communication
- Timing
- Interaction Overview 
- Multiple output formats supported:
- Image formats (PNG, SVG, PDF)
- Class-based architecture with DiagramBuilder and UMLDiagramBuilder
- This …

feat(tools): add diagram tool to Strands tools repository

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-and-push.yml
pyproject.toml

These changes:
- Provide a single command `hatch run prepare` to run all required commands
- Streamline the GitHub PR template
- Avoids running the github workflows un-necessarily
These changes were originally made to the SDK a while ago:
- Streamlining contributions: strands-agents/sdk-python/pull/221
- Not running workflows on un/approvals: strands-agents/sdk-python/pull/516
----
This GitHub PR uses the updated PR template
N/A
N/A
Other (please describe): Streamline contributions
How have you tested the change?  Verify that the changes do not break functionality or introduce warnings in consuming repositories: agents-docs, agents-tools, agents-cli
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Update github contributing flow

---

src/strands_tools/memory.py
tests/test_memory/test_memory_client.py

This PR fixes the memory tool data source type detection bug reported in issue #90.
The memory tool was hardcoded to assume 'CUSTOM' data source type, causing failures when users had multiple data sources where the first one wasn't CUSTOM type (e.g., S3 data sources).
- **Added  method** that properly identifies data source types
- **Prioritizes CUSTOM data sources** but falls back to first available if none found  
- **Updated all operations** (store_document, delete_document, get_document) to use proper type detection
- **Enhanced error messages** for unsupported data source types with clear guidance
- **Updated tests** to mock the new get_data_source API calls
1. **Robust Data Source Discovery**: Searches through ALL data sources, not just the first
2. **Type Validation**: Explicitly …

fix(memory): implement data source type detection for multiple data source support

---

src/strands_tools/shell.py
tests/test_shell.py

This PR migrates the shell tool from the legacy TOOL_SPEC dictionary format to the modern @tool decorator pattern, following the new Strands SDK conventions.
- Replace TOOL_SPEC dictionary with @tool decorator
- Update function signature to use typed parameters instead of ToolUse
- Remove toolUseId dependency from return format
- Modernize parameter handling and validation
- Maintain all existing functionality and features
- Update all test cases to use new function signature
- Remove toolUseId assertions from tests
- Add new test for non_interactive parameter
- Ensure backward compatibility
Part of the broader effort to modernize strands-agents tools to use the @tool decorator pattern.
No documentation changes required - function behavior remains identical.
Migration to @tool decorator. …

feat(shell): migrate to @tool decorator pattern

---

README.md
pyproject.toml
src/strands_tools/rss.py
tests/test_rss.py

This PR introduces an RSS feed management tool, enabling agents to interact with RSS feeds for information gathering, content monitoring, and data integration tasks.
This tool provides comprehensive RSS feed management capabilities:
- Fetch: Retrieve feed content from URLs without subscribing
- Subscribe: Add feeds to a subscription list
- Unsubscribe: Remove feed subscriptions
- List: Display all subscribed feeds
- Read: Access entries from subscribed feeds
- Update: Refresh feeds with new content
- Search: Find entries matching specific queries
- Categories: List all categories/tags across feeds
- Automated content aggregation and curation
- Real-time monitoring of news and updates
- Integration of RSS data into other agent workflows
- Content analysis and trend tracking
- This tool can …

feat(tools): add rss tool to Strands tools repository

---

README.md
pyproject.toml
src/strands_tools/use_computer.py
tests/test_use_computer.py

- This tool was tested on macOS, so some features may not work on Windows/Linux
- **Basic Computer Control:**
- Mouse operations (click, move, drag)
- Keyboard input (typing, key combinations, hotkeys)
- Scrolling (vertical and horizontal)
- Application management (open, close, focus)
- **Screen Analysis:**
- Screenshot capture and analysis
- OCR text detection using Pytesseract
- Coordinate mapping for detected elements
- Text grouping and line organization
- Return the image as bytes to the LLM model
- **Cross-Platform Support:**
- Windows, macOS, and Linux compatibility
- Platform-specific optimizations (e.g., native macOS double-click)
- Adaptive application naming conventions
- Utilizes `pyautogui` for computer control
- Integrates OpenCV and Pytesseract for image processing and text …

feat(tools): add use_computer tool to Strands tools repository

---

pyproject.toml
src/strands_tools/a2a_client.py
tests/test_a2a_client.py

Upgrade to `ClientFactory` to address warnings in logs:
> DeprecationWarning: A2AClient is deprecated and will be removed in a future version. Use ClientFactory to create a client with a JSON-RPC transport.
Other (please describe): General refactor
How have you tested the change?  Verify that the changes do not break functionality or introduce warnings in consuming repositories: agents-docs, agents-tools, agents-cli
----

refactor(a2a): upgrade to ClientFactory

---

src/strands_tools/a2a_client.py

This change adds optional push notification capabilities to the A2AClientToolProvider, enabling real-time webhook notifications when agent tasks complete.
Changes:
- Add `webhook_url` and `webhook_token` parameters to A2AClientToolProvider constructor
- Create PushNotificationConfig automatically when both parameters are provided
- Include push notification configs in ClientFactory configuration
- Update class docstring to document new push notification feature
- Maintain full backward compatibility with existing usage
These parameters are now optional constructor arguments in A2AClientToolProvider, providing webhook notification capabilities while maintaining backward compatibility.
**Backward Compatibility**: There are no functional changes to existing A2AClientToolProvider usage - all …

Add push notification support to A2AClientToolProvider

---

src/strands_tools/a2a_client.py

Converts `webhook_url` and `webhook_token` attributes in the `A2AClientToolProvider` class to private variables by prefixing them with underscores (`_webhook_url` and `_webhook_token`). 
Other (please describe): Code refactoring - improved encapsulation
How have you tested the change?  Verify that the changes do not break functionality or introduce warnings in consuming repositories: agents-docs, agents-tools, agents-cli
----

chore(a2a): private webhook variables

---

src/strands_tools/code_interpreter/code_interpreter.py

- Add docstring to code_interpreter to allow usage with other agents (like langgraph)
BREAKING CHANGE: None - It’s only an improvement with a comment
Refs:  #214
Add a docstring to code_interpreter. With this comment the tool can be used with langgraph
No issues
Other: add a docstring for one function
No broken tests
- [] Any dependent changes have been merged and published
----

fix(code_interpreter): improve code_interpreter docstring

---

src/strands_tools/environment.py
src/strands_tools/slack.py
tests/test_http_request.py
tests/test_nova_reels.py
tests_integ/test_memory_tool.py

This PR addresses breaking changes introduced by the SDK refactor that removed ephemeral system prompt overrides (strands-agents/sdk-python#344). The changes ensure proper agent model inheritance and callback handling in the Slack tool.
- **System Prompt Assignment**: Updated to use  pattern instead of ephemeral overrides
- **Model Inheritance**: Pass parent agent model to child agents to prevent default model usage  
- **Callback Handler**: Add callback_handler inheritance for proper event handling
- **Test Cleanup**: Remove unused test assertion in nova_reels
- Customers were experiencing issues where agents used default models instead of the parent agent's model
- System prompt changes weren't working due to SDK refactor removing temporary override functionality
- …

fix(slack): adapt to SDK system prompt changes and improve agent model inheritance

---

src/strands_tools/handoff_to_user.py
tests/test_handoff_to_user.py

This PR improves the user experience in the `handoff_to_user` tool by enhancing the prompt message displayed to users. The change makes it clearer what the agent is requesting by including the agent's message in the user input prompt.
This is essentially important for customers who do not have `STRANDS_TOOL_CONSOLE_MODE` enabled.
**Changes made:**
- Modified the user input prompt in `handoff_to_user.py` to include the agent's message before asking for user response
- Updated the corresponding test to reflect the new prompt format
- The prompt now shows: `"Agent requested user input: {message}\nYour response: "` instead of just `"Your response: "`
This improvement provides better context to users about what the agent is asking for, making the interaction more intuitive and user-friendly. …

fix: Improve print in handoff to user

---

src/strands_tools/handoff_to_user.py
tests/test_handoff_to_user.py

Fix linting error in the tool handoff_to_user:
```
src/strands_tools/handoff_to_user.py:182:121: E501 Line too long (135 > 120)
tests/test_handoff_to_user.py:66:121: E501 Line too long (148 > 120)
```
Bug fix
New Tool
Breaking change
Documentation update
Other (please describe):
How have you tested the change?  Verify that the changes do not break functionality or introduce warnings in consuming repositories: agents-docs, agents-tools, agents-cli
----

fix: linting error in hand_off_to_user

---

src/strands_tools/browser/agent_core_browser.py
src/strands_tools/code_interpreter/__init__.py
src/strands_tools/code_interpreter/agent_core_code_interpreter.py
tests/browser/test_agent_core_browser.py
tests/code_interpreter/test_agent_core_code_interpreter.py
tests_integ/code_interpreter/test_agent_core_code_interpreter_custom_identifier.py

This PR adds support for custom code interpreter identifiers to the `AgentCoreCodeInterpreter` class, enabling users to specify custom AWS Bedrock AgentCore code interpreter environments while maintaining full backward compatibility.
- **Custom Identifier Support**: Users can now specify custom code interpreter identifiers via the `identifier` parameter
- **Full Backward Compatibility**: Existing code continues to work unchanged with default AWS code interpreter
- **Comprehensive Testing**: 56 tests covering all functionality including new custom identifier features
- **Clear Documentation**: Updated documentation with usage examples and clear guidance
- **Constructor Enhancement**: Added optional `identifier` parameter to `AgentCoreCodeInterpreter.__init__()`
- **Session …

feat: Add custom code interpreter identifier support to AgentCoreCodeInterpreter

---

src/strands_tools/browser/browser.py

Bug Fix: Properly handle ```persistent_context``` sessions in LocalChromiumBrowser by avoiding calls to ```new_context()``` on a persistent session.
This PR fixes a bug where initializing a LocalChromiumBrowser session with ```persistent_context=True``` caused failures because ```launch_persistent_context()``` returns a ```BrowserContext``` rather than a ```Browser```. Previously, the tool attempted to call ```new_context()``` on this object, which is invalid.
Resolves #204 
**File**: ```src/strands_tools/browser.py```
- Updated session creation logic to distinguish between persistent and non-persistent sessions.
- If the returned object is a ```Browser``` (non-persistent case), a new context and page are created.
- If the returned object is a ```BrowserContext``` (persistent case), the …

fix(Browser): prevent new_context calls when using persistent_context

---

pyproject.toml
src/strands_tools/http_request.py

Remove `readabilipy` dependency to eliminate automatic npm package installation. The `http_request` tool's `convert_to_markdown` feature now uses only `markdownify` for HTML-to-markdown conversion.
**Changes:**
- Removed `readabilipy` from dependencies
- Simplified `extract_content_from_html` to use only `markdownify`
- Maintains same API and functionality
Bug fix
----

fix: Remove readabilipy dependency

---

README.md
pyproject.toml
src/strands_tools/chat_video.py
src/strands_tools/search_video.py
tests/test_chat_video.py
tests/test_search_video.py

Added two new video analysis tools using TwelveLabs' AI models:
1. **search_video**: Semantic video search using TwelveLabs' Marengo model for natural language queries against video content
2. **chat_video**: Interactive video analysis using TwelveLabs' Pegasus model for Q&A about video content
Both tools support multi-modal analysis (visual and audio), with chat_video offering video upload capabilities and caching.
Documentation PR not made
Comprehensive testing implemented for both video tools:
- Added test suites covering success cases, error handling, and edge cases
- Mock TwelveLabs API interactions for reliable testing  
- Video upload caching functionality tested
- All video tool tests pass consistently (20/20)
* `hatch fmt --linter` ✅ (line length issues resolved)
* `hatch fmt …

feat: Add Twelve Labs Video tools
